#ifndef HARDCODEDDATA_H
#define HARDCODEDDATA_H

#define DECIMAL_BASE (int)10
#define READ_ONE_CHAR 1
#define WAIT_TIME 20000
#define MISSION_FILE_NAME_ARGUMENT 1
#define PRIORITY_FILE_NAME_ARGUMENT 2
#define MISSIONS_NUM_ARGUMET 3
#define THREADS_NUM_ARGUMET 4
#define START_OF_LINE_LEN 30
#define COMMA_AND_SPACE_LEN 2
#define WAIT_TIME_READ_LOCK 200
#define WAIT_TIME_WRITE_LOCK 200
#define FAILURE_CODE -1

#endif 
